In [3]:
import datetime as dt
import pandas as pd
import numpy as np

In [8]:
# Set Peak
peak_month = [3,4,5,6,7,8,9,10,11,12,1,2]
peak_arr = [95,95,94,90,91,72,66,87,91,85,100,95]

peak_year = 2020
peak_date = list()
peak_df = pd.DataFrame(columns=["peak"])

for idx,_ in enumerate(peak_month):
    peak_date.append(
        dt.datetime(
            peak_year,
            _,
            1
        )
    )
    peak_df = peak_df.append({
        "peak": peak_arr[idx] 
    },ignore_index=True)
    
peak_df.index = peak_date
peak_df

           peak
2020-03-01   95
2020-04-01   95
2020-05-01   94
2020-06-01   90
2020-07-01   91
2020-08-01   72
2020-09-01   66
2020-10-01   87
2020-11-01   91
2020-12-01   85
2020-01-01  100
2020-02-01   95